baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Ethan Woelbern
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
       # - name: Books
       #   url: books/
       #   weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
       # - name: Data
       #   url: data/
       #   weight: 4 
       # - name: Blog
       #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
       #   weight: 6

params:
    description: "This website hosts Ethan Woelbern's research papers, books (perhaps one day), course materials, data, curriculum vitae, and contact information."
    author: Ethan Woelbern
    # googleAnalyticsID: G-XXXXX
    DateFormat: September 2026
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: [books, courses, papers, data]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ethan Woelbern
          subtitle: "I am a student of Literature, Religious Studies and Philosophy at UC Santa Barbara. My research focuses on the difficulty of moral recognition in second personal relations in the work of Hegel, Stanley Cavell, and Ludwig Wittgenstein. I also work on the relation between ethics and literature."
          imageUrl: profile.jpg
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
           # - name: Data
           #   url: data/
           # - name: Books
           #   url: books/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
           # - name: Archive
           #   url: archive/
           # - name: Blog
           #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: Ethan Woelbern Academic CV .pdf
        - name: Email
          url: mailto:ewoelbern@ucsb.edu
        - name: Zoom
          url: https://ucsb.zoom.us/profile
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=user
        - name: GitHub
          url: https://github.com/ewoelbern
        - name: Substack
          url: https://user.substack.com

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Ethan Woelbern
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2